# Generated by Django 3.0.6 on 2020-05-28 13:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailtrans', '0009_create_initial_language'),
        ('wagtailimages', '0022_uploadedimage'),
        ('cms', '0004_auto_20200528_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeIndexPage',
            fields=[
                ('translatablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailtrans.TranslatablePage')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailtrans.translatablepage',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='theme_section',
            field=models.ForeignKey(blank=True, help_text='Featured section for the homepage. Will display all themes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailtrans.TranslatablePage', verbose_name='Theme section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='theme_section_intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='theme_section_title',
            field=models.CharField(blank=True, help_text='Title to display above the theme section', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ThemePage',
            fields=[
                ('translatablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailtrans.TranslatablePage')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themepages', to='cms.Theme')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailtrans.translatablepage',),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='themes',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='articlepages', to='cms.Theme', verbose_name='Themes'),
        ),
    ]
