# Generated by Django 3.0.6 on 2020-06-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_menu_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
