# Generated by Django 3.0.6 on 2020-06-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_companylogo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyLogo',
        ),
    ]
