# Generated by Django 3.0.6 on 2020-06-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailtrans', '0009_create_initial_language'),
        ('cms', '0015_textpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textpage',
            name='translatablepage_ptr',
        ),
        migrations.DeleteModel(
            name='CompanyLogo',
        ),
        migrations.DeleteModel(
            name='TextPage',
        ),
    ]
