# Generated by Django 3.0.6 on 2020-06-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_textpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_nl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_en',
            field=models.CharField(help_text='Title of menu item that will be displayed', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_fr',
            field=models.CharField(help_text='Title of menu item that will be displayed', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_nl',
            field=models.CharField(help_text='Title of menu item that will be displayed', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_nl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
